Dongstep4
moto3d/java-racingcar pull request #9
Opened 2023-04-15 08:47 UTC by d-h-k

to @ghojeong 

-----

### git 관련 
- git 관련 약간의 에러가 있어서, 알려주신 방법대로 dongstep4 를 새로 만들고, 그동안의 작업분량 commit 을 cherry-pick 기능을 사용해서 가져왔습니다! 깃헙 관련 내용 알려주셔서 다시한번 감사합니다!

-----

안녕하세요 리뷰어님 Step4 - 자동차 경주(우승자) PR 올립니다
이번 미션을 진행하면서 제가 분석한 기능적 & 비기능적 요구사항들을 정리했는데요
테스트가 있는것과 테스트가 없는것으로 나누어서 이행여부를 체크해봤습니다.

## 테스트가 있는 요구사항

- [car class]
  - [x] 자동차 이름은 5자를 초과할수 없다
  - [x] 자동차에 이름을 부여할 수 있다

- [input]
  - [x] 자동차 이름을 입력받을떄, 쉼표를 기준으로 구분한다
  - [x] 입력한 이름의 숫자 만큼 자동차 대수를 생성한다

- [output]
  - [x] 전진하는 자동차를 출력할 때 이름을 같이 출력한다

- [carRacing] 
  - [x] 자동차 경주 게임을 완료한 후 누가 우승했는지를 알려준다
  - [x] 우승자는 여러명일 수 있다

### 테스트가 없는 요구사항
- [ ] 자동차는 자동차 이름과 위치 정보를 가지는 Car 객체를 추가해 구현
- [ ] 인덴트는 1단계만
- [x] 기능을 구현하기 전에 README.md 파일에 구현할 기능 목록을 정리
- [x] 커밋은 기능 단위로

### 이외 리뷰받은 사항중, 이번 스텝에서의 개선사항
- [ ] 컬렉션은 복사해서 전달하기
- [ ] 2차원 컬렉션 `List<List<String>>` 제거
- [ ] 불필요하게 복잡성을 늘리지 않기

입니다. 이번 스텝도 잘 부탁드리겠습니다!

2023-04-15 11:08 UTC, ghojeong requested changes
Dong! 
람다식을 극한으로 활용하려 하신게 눈에 뜨네요.
특히 불변성을 지키려고 많은 노력을 하신게 보여서 대단하다고 생각했습니다.
읽으면서 제 개인 의견과 함께 궁금했던 부분들 남겨보았습니다.

2023-04-15 11:08 UTC, ghojeong commented on src/main/java/step3/model/Car.java
> +    };
```suggestion
    private void validate(String name) {
        if (name.length() > 5) {
            throw new IllegalArgumentException("자동차 이름은 5자를 초과할수 없다");
        }
    }
```

평범한 void 함수 대신에 UnaryOperator 를 사용하신 의도가 있으시나요?
이건 정말 궁금해서 여쭈어봅니다.
꼭 장점이 아니더라도, Dong 은 어떨때 UnaryOperator 를 사용하시는지 궁금해서 여쭈어봅니다.

가령 저는 다음과 같은 기준으로 람다식을 사용합니다.
error 를 throw 하는 것처럼 side-effect 가 있는 로직이라면, 저는 전통적인 절차지향 스타일로 메서드를 선언하고,
람다식을 사용할 때에는 가능한 side-effect 를 스스로 최소화하는 방향으로 구현을 합니다.

하지만 이건 저만의 스타일과 저만의 코딩 스타일인지라,
Dong 은 람다식을 어떻게 활용하시는지 궁금해서 여쭈어봅니다.

2023-04-15 11:08 UTC, ghojeong commented on src/test/java/step3/model/CarTest.java
> +        }).isInstanceOf(IllegalArgumentException.class);
테스트만 보아서는 IllegalArugmentException 이 발생한 이유가,
정말로 5자를 초과해서 인지, 아니면 중간의 다른 로직이 IllegalArgumentException 을 발생시킨것인지 알기 어렵습니다.
이럴 때는 저는 명시적으로 Exception 의 에러 메시지까지 확인하는 테스트를 작성하거나,
발생한 Exception 객체 이름만 보고도 Exception 이 발생한 상황을 유추가능하게끔 커스텀 예외를 작성하는 편입니다.

2023-04-15 11:08 UTC, ghojeong commented on src/test/java/step3/model/CarTest.java
> +    }
actual 과 expected 를 비교하는 assertion 이 없는데,
위의 5자를 초과할수 없다 만으로도 충분히 자동차 이름이 5자 이하라는 사실을 테스트할 수 있지 않을까 하고 생각합니다.
저는 테스트를 production 코드와 마찬가지로 유지보수해야하는 코드라 생각하기 때문에,
유의미하지 않는 테스트라면 굳이 남겨놓지 않는 것을 추천하는 편입니다.

2023-04-15 11:08 UTC, ghojeong commented on src/main/java/step3/model/Match.java
> +        return collect1;
이건 next-step TDD 교육과정을 쉽게 통과할 수 있는 꿀팁인데,
자동차 미션과 로또 미션까지는 람다식을 미리부터 많이 활용하려 하기보다는,
전통적인 "Interface" 설계에 더 시간을 많이 쓰기를 추천드립니다.

결국 자바의 람다는 제대로된 함수형을 지원하지 못하고,
interface 기반으로 객체를 만드는 거라서,
교육과정상 자동차 미션과 로또 미션에서 interface 설계에 얼마만큼 공을 들였냐를 피드백하게 됩니다.
벌써부터 람다를 많이 활용하면, 리뷰 받을 수 있는 경험이 하나 줄어든다고 생각하빈다.
세번째 미션인 사다리타기부터 어차피 람다식을 원하던 원치않던 주구장창 쓰시게 될테니깐, 다음 미션인 로또에서는 한번 전통적인 객체지향 방식으로 프로젝트를 구현해보시는 걸 추천드려봅니다.

2023-04-15 11:08 UTC, ghojeong commented on src/test/java/step3/model/MatchTest.java
>      }
assert 를 여러번 하게 된다면, assertAll 혹은 SoftAssertions 를 활용해보시기를 추천드립니다.

2023-04-15 11:08 UTC, ghojeong commented on src/main/java/step3/present/DisplayRaceVO.java
> +    private final Car car;
VO 객체 매우 훌륭하게 선언해주신 것 같습니다. 👍 
보통 사람들이 final 로만 해두면 Value Object 라고 착각하시는 분들이 많은데,
제대로된 VO 려면 내부 멤버들 또한 불변이어야 합니다.
Result 와 Car 둘 모두 getter 만 있고 Value 가 변경될 수 있는 여지가 없기 때문에,
매우 훌륭한 VO 라고 부를 수 있을 것 같습니다.

2023-04-15 11:08 UTC, ghojeong commented on src/main/java/step3/model/Result.java
> +        return new ArrayList<>(positionList);
방어적 복사 좋습니다. 👍

2023-04-15 11:08 UTC, ghojeong commented on src/test/java/step3/present/InputPresentTest.java
> +        System.setIn(new ByteArrayInputStream(inputString.getBytes()));
이건 저도 진짜 몰라서 궁금해서 여쭈어보는데,
AfterEach 를 할 때마다 `System.setIn(System.in);` 을 왜 해주어야하는지 궁금해서 여쭈어봅니다.
이것은 무슨 세팅을 하는 건가요?

2023-04-15 11:08 UTC, ghojeong commented on src/test/java/step3/present/OutputPresentTest.java
> +        assertThat(outputStream.toString().trim()).isEqualTo(answer);
입력된 값에 따라 렌더링되는 최종 결과인 `answer` 를 확인하는 테스트 같아 보이는데,
**AB-TEST** 라고 이름 붙이신 이유가 궁금해서 여쭈어봅니다.
2가지 버전을 만들어서 고객의 반응을 확인하는 그 A/B 테스트가 맞나요?

2023-04-15 13:07 UTC, d-h-k commented on src/main/java/step3/model/Car.java
> +    };
요거는 람다식에 큰 의미가 있다기 보다는 편의성때문에 쓰는데요 예를들어서.. 
`void validate(String name)`  이런식으로 함수를 쓰면 한줄을 무조건 더 써야하는데
`UnaryOperator<String> validateName` 으로 쓰면 validate 를 위해서 한줄을 더 추가하지 않아서 썻습니다..

2023-04-15 13:12 UTC, d-h-k commented on src/test/java/step3/model/CarTest.java
> +    }
듣고보니 해당 테스트코드는 크게 의미없는듯 합니다. 삭제하겠습니다!

2023-04-15 13:15 UTC, d-h-k commented on src/main/java/step3/present/DisplayRaceVO.java
> +    private final Car car;
감사합니다!

2023-04-15 13:15 UTC, d-h-k commented on src/main/java/step3/model/Result.java
> +        return new ArrayList<>(positionList);
감사합니다!

2023-04-15 13:29 UTC, d-h-k commented on src/test/java/step3/present/InputPresentTest.java
> +        System.setIn(new ByteArrayInputStream(inputString.getBytes()));
해당부분은 `System.setIn(다른인풋스트림)` 을 썻기때문에, 콘솔입력을 받지 못하는걸로 알고있습니다. 

JVM 도 프로세스라서, 실행시에 stdin, stdout, stderr 라는 3개의 파일스트림을 열고 프로세스가 종료될떄 close 되는데, 원래 stdin 으로 연결된 스트림을 잠깐 바꿔서 해당 테스트코드의 입력스트림으로 바꿨다가 원상복구하는 코드로 파악하고 있습니다

2023-04-15 13:41 UTC, d-h-k commented on src/main/java/step3/model/Match.java
> +        return collect1;
요부분은 말씀하신대로 interface 설계 하는 방식으로 진행하겠습니다

2023-04-15 13:42 UTC, d-h-k commented on src/test/java/step3/present/OutputPresentTest.java
> +        assertThat(outputStream.toString().trim()).isEqualTo(answer);
제가 AB 를 너무 자의적으로 해석한 부분이 있는데, 문구를 수정하겠습니다

2023-04-15 13:44 UTC, d-h-k commented on src/test/java/step3/present/OutputPresentTest.java
> +        assertThat(outputStream.toString().trim()).isEqualTo(answer);
AB TEST 가 마케팅이나 가설검증에서는 많이 쓰이는데, 저는 A를 입력했을때 > 실패한다 B 입력시> 성공한다 같이 같은 내용을 성공하는 케이스와 실패하는 케이스로 나눠서 썻는데 말씀을 들어보니 별로 좋지못한 부분이였네요 코멘트 감사합니다!!

2023-04-15 15:40 UTC, d-h-k commented on src/test/java/step3/model/CarTest.java
> +        }).isInstanceOf(IllegalArgumentException.class);
메시지까지 확인하는 테스트를 작성 하겠습니다.

매 Exception 마다 커스텀익셉션을 만드는건 과한거같아서 ㅎ.. ㅠ

2023-04-15 15:41 UTC, d-h-k commented on src/main/java/step3/model/Match.java
> +        return collect1;
아니.. 람다를 없애려고 리팩토링을 시작했는데.. 더 람다범벅이 되버렸어요... 어떻게하죠

2023-04-15 17:16 UTC, ghojeong commented on src/test/java/step3/present/InputPresentTest.java
> +        System.setIn(new ByteArrayInputStream(inputString.getBytes()));
오호 그렇군요!
덕분에 저도 배워갑니다.
감사합니다!

2023-04-15 17:17 UTC, ghojeong commented on src/test/java/step3/present/OutputPresentTest.java
> +        assertThat(outputStream.toString().trim()).isEqualTo(answer);
오호 그런 용도로 사용하시는 거라면 저는 괜찮다고 생각합니다!
리뷰어의 피드백은 꼭 수정사항 요청라기 보다는,
리뷰어도 궁금해서 질문을 했다는 느낌으로 받아들여주시면 좋을것 같아요!

2023-04-15 17:18 UTC, ghojeong commented on src/main/java/step3/model/Car.java
> +    };
오호 그렇군요!
그런 의도라면 확실히 편리한것 같습니다!

2023-04-16 01:37 UTC, ghojeong commented on src/main/java/step3/model/Car.java
> +    };
어제 제가 왜 UnaryOperator 가 문제될 것이 없는데 왜 의도에 대해 궁금해했을까 다시 고민을 해보았는데,
아무래도 제가 코틀린으로 개발하던 시절에 습관이 남아서 그랬던것 같습니다.
코틀린에서는 UnaryOperator 와 비슷하지만, 의미적으로 다르게 쓰는 [apply, with, let, also, run](https://medium.com/@limgyumin/%EC%BD%94%ED%8B%80%EB%A6%B0-%EC%9D%98-apply-with-let-also-run-%EC%9D%80-%EC%96%B8%EC%A0%9C-%EC%82%AC%EC%9A%A9%ED%95%98%EB%8A%94%EA%B0%80-4a517292df29) 가 있어서요.
가독성 측면에서 apply, with, let, also, run 을 영어 의미에 맞게 사용했는가를 코드리뷰 할 때 해주곤 했는데,
하지만 Java 에서는 오직 apply 만 한개 존재하니, 지금처럼 Dong 이 사용하신게 적절한것 같습니다.

2023-04-24 10:26 UTC, merged